development:
  adapter: postgresql
  database: autobiographer_development
staging:
  adapter: postgresql
  database: autobiographer_development
test:
  adapter: postgresql
  database: autobiographer_test
production:
  adapter: postgresql
  database: autobiographer_production
