development: &defaults
  app_id: 174949782521803
  client_id: 7d3d7aea5f3fa8011b2fea0294257133
  client_secret: 558ee62beac6d6cde77000dae9cee0f6
  perms: read_stream,publish_stream,offline_access,manage_pages,user_checkins,friends_checkins,user_photos

test:
  <<: *defaults

production:
  <<: *defaults