development: &defaults
  client_token: 1WGMDSXQD03NGGKY4PDMTM5QCYK20CF42L03XP10WP20A0LO
  client_secret: LBN2M1YOKHPRDXBRCHJOIHDQCADUHR4PQNN4KMIEEDINK0D0

staging:
  <<: *defaults

test:
  <<: *defaults

production:
  client_token: 2QNVKDKYAOUBNPKUPXDGAQ15R3TKFFISNKEYMFCTQV0AOSSJ
  client_secret: QMA4WUHEB0FLD1JL414DARMOHFKKOLBNYAGOCVXNQB5QAZ1B