development: &defaults
  client_token: icutAepU7WKSlMxdHVFmeg
  client_secret: 3aZ4HaYmqwxhGYEyIcPNNfj0U1H0mGxk93xekGbsrQ

test:
  <<: *defaults

production:
  client_token: TJukfSBdpE8IArYifBwTQ
  client_secret: 92CcBJjoGg0MnGdVaQL0UKSzi4YuqfbglGJtrmR8PRU